apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: tanzu-application-platform
  description: Everything related to the Tanzu Application Platform
  links:
    - url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/index.html
      title: Tanzu Application Platform Documentation
      icon: docs
    - url: https://network.tanzu.vmware.com/
      title: Tanzu Network
      icon: download
spec:
  owner: tanzuplatform
