apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: app=application-live-view-server
  description: Tanzu Application Live View Server Component
  name: application-live-view-server
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: tanzuplatform
  system: application-live-view
  type: service
