apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  description: Service Bindings Operator System
  name: service-bindings-operator
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  domain: tap
  owner: platform-team
