apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  description: TAP Telemetry System
  name: tap-telemetry
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  domain: tanzu-application-platform
  owner: tanzuplatform
