apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tanzu-application-platform
  description: The Tanzu Application Platform
spec:
  targets:
    - ./groups/team.yml
    - ./domains/domain.yml
    - ./systems/system.yml
    - ./components/tap-gui.yml
    - ./components/contour.yml
    - ./components/kapp-controller.yml
    - ./components/appsso.yml

