apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: default-org
  description: The Default Organization
  links:
    - url: https://tanzu.vmware.com/support
      title: Tanzu Support Website
spec:
  type: organization
  profile:
    displayName: Default Organization
    email: demo@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [default-team]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: default-team
  description: Default Team
spec:
  type: team
  profile:
    displayName: Default Team
    email: team-a@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: default-org
  children: []
