apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/component=webhook,app.kubernetes.io/instance=cert-manager,app.kubernetes.io/name=webhook
  description: Cert Manager Webhook Component
  name: cert-manager-webhook
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: tanzuplatform
  system: cert-manager
  type: service
