apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  description: Application SSO System
  name: app-sso
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  domain: tanzu-application-platform
  owner: tanzuplatform
