apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  description: Metadata Store System
  name: metadata-store
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  domain: tap
  owner: platform-team
