apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: app=informer
    backstage.io/kubernetes-namespace: tap-telemetry
  description: TAP Telemetry Informer Component
  name: tap-telemetry-informer
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: tanzuplatform
  system: metadata-store
  type: service
