apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tap-install
  description: The package installs for the Tanzu Application Platform
  tags:
    - installs
    - tanzu-application-platform
  annotations:
    'backstage.io/kubernetes-namespace': 'tap-install'
spec:
  type: service
  lifecycle: production
  owner: tanzuplatform
  system: tanzu-application-platform
